### ISSUE TITLE
Crash on first launch without Internet

### ISSUE THREAD

**Issue by pcfaktor** [SoftTeco/AndroidAppTemplate#156]
**Description**
Version: 99
The application crashes when first launched without internet connection. It looks like it's something with FCM initialization.

**Steps:**

1. Install the application;
2. disable all network interfaces;
3. Start the application;

**Actual Result**: The application crashes after requesting permission to display notifications.

**Comment by bogdan-stolyarov** [comment]
@pcfaktor Do you update the google-services.json file before making a build?

**Comment by pcfaktor** [comment]
@bstolyarov This is happening with a build from AppCenter
