### ISSUE TITLE
Create common Primary button component

### ISSUE THREAD

**Issue by bstolyarov** [SoftTeco/AndroidAppTemplate#47]
Create a common button component with `loading` parameter and loader after the label inside the button. 
Show loading after clicking on the button, while api call(for example) is executing. 
While the loader is loading button can not be clicked.
It should avoid double-clicking on the buttons. 

name for component: AppPrimaryButton

**Comment by anastasiaShpakava** [comment]
`Show loading after clicking on the button,` - where should be loader?

**Comment by anastasiaShpakava** [comment]
If this loader depends on API call executing, for what do we have the loader at the top of the screen?

**Comment by bstolyarov** [comment]
> If this loader depends on API call executing, for what do we have the loader at the top of the screen?

Then loader in top of the screen could be removed
